/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication5;

import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DeadTrigger
 */
public class PizaOrder extends javax.swing.JFrame  {

    /**
     * Creates new form PizaOrder
     */
   
    public PizaOrder() {
        this.LQ1 = new LinkedQueue();
        
        initComponents();
        scaleImage3("Red Photo Background Christmas Food and Drink Menu.png",jLabel7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Order = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        WorkOrder = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 100, 400, 100));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Please Place Order");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 120, 170, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 190, 50, 14);
        jPanel1.add(Name);
        Name.setBounds(150, 180, 220, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Order");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 230, 40, 14);
        jPanel1.add(Order);
        Order.setBounds(150, 220, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Amount");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 270, 50, 14);

        Amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AmountKeyTyped(evt);
            }
        });
        jPanel1.add(Amount);
        Amount.setBounds(150, 260, 220, 30);

        jButton1.setText("Add Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 310, 83, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Working on order");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 360, 159, 22);
        jPanel1.add(WorkOrder);
        WorkOrder.setBounds(80, 410, 320, 29);

        jButton2.setText("Order Completed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 470, 130, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Welcome To Fast Food");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 50, 201, 22);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 480, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int i =0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String order =Order.getText().toString();
        String name = Name.getText().toString();
        if(LQ1.size()==0)
        
        System.out.print("Add :  "+order);
        LQ1.add("Name : " + name +"\n  Order :"+Amount.getText().toString()+" "+order);
        if(i ==0)
        {
            WorkOrder.setText("Order of : "+ "Name : " + name +"  Order : "+Amount.getText().toString()+" "+order);
        }
        Order.setText("");
        Name.setText("");
        Amount.setText("");
        i++;
    }//GEN-LAST:event_jButton1ActionPerformed
     
    
    public  void scaleImage3(String url ,javax.swing.JLabel  lbl )
    {
        System.out.println("changed image");
        ImageIcon imgicon = new ImageIcon("src\\Images\\"+url); 
        Image img = imgicon.getImage();
        Image imgscale = img.getScaledInstance(lbl.getWidth(),lbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        lbl.setIcon(scaledIcon);
        
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(LQ1.size() == 0){
       JOptionPane.showMessageDialog(this,"There Is no Order Remaining"); 
        } else  JOptionPane.showMessageDialog(this,"Order of : "+ LQ1.remove()+ " Completed" );
       
         System.out.println(LQ1.size());
         
        WorkOrder.setText(LQ1.peek().toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
      if(!(Character.isDigit(c))  )
        {
            if((c!=KeyEvent.VK_BACK_SPACE) && (c!=KeyEvent.VK_DELETE)){
            getToolkit().beep();
            }
           evt.consume();
            
        }
    }//GEN-LAST:event_AmountKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizaOrder().setVisible(true);
            }
        });
    }
    public LinkedQueue LQ1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Order;
    private javax.swing.JLabel WorkOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
